name: Print Changed Files

on:
  pull_request:
    types:
      - opened
      - synchronize 

jobs:
  print_changed_files:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: List Changed Files
      run: |
        # Get the list of changed/added files in the pull request
        git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} >> changed_files.txt

        # Print the contents of the file with changed/added file names
        cat changed_files.txt

    - name: Clean up
      run: rm changed_files.txt
