name: Validate changes on prod
on:
  pull_request:
    types:
      - opened

jobs:
  Validate_Production:
    runs-on: ubuntu-latest
    steps:
      - name: Install Salto CLI
        run: |
          curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
          tar xvzf linux-x64.tar.gz
        
      - name: Run Deploy Validation on Production
        run: |
          ./salto-cloud deployment validate -b ${{ github.event.pull_request.head.ref }} 
        env: 
          SALTO_API_TOKEN: ${{ secrets.SALTO_API_TOKEN }}


